[package]
name = "vizia_file_dialog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.2.0"
chrono = "0.4.24"
vizia = { git = "https://github.com/vizia/vizia.git" }
